import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Trello Clone Using Typescript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Hello>Nextjs + Styled Components</Hello>
      </main>


    </div>
  )
}

export default Home

/* Sample Css */
const Hello = styled.p`
font-size: 20px;
`