import type { NextPage } from 'next'
import Head from 'next/head'
import { AppContainer } from '../styles/styles'
import { Column } from './components/Column'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Trello Clone Using Typescript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <AppContainer>
          <Column text="Todo:" />
        </AppContainer>
      </main>


    </div>
  )
}

export default Home